version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vmshare_app
    restart: unless-stopped
    working_dir: /VM_share/app
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus
    # publish the SAME port your server expects
    ports:
      - "8000:8000"
    # mount your tree 1:1 so ALL subfolders/files are there
    volumes:
      - ${HOST_ROOT}/VM_share:/VM_share
      - ${HOST_ROOT}/base_images:/base_images:ro
      - ${HOST_ROOT}/iso:/iso:ro
      - ${HOST_ROOT}/cloud:/cloud
      - ${HOST_ROOT}/logs:/logs
      - ${HOST_ROOT}/custom:/custom
      - ${HOST_ROOT}/overlays:/overlays
    # optional hardening you can enable later:
    # read_only: true
    # tmpfs: ["/tmp", "/run"]
    # cap_drop: ["ALL"]

networks:
  default:
    name: vmshare_net
