services:
  app:
    build: .
    container_name: vmshare-app
    expose: ["8000"]
    env_file: [.env]          # <-- this loads .env into the app container
    extra_hosts: 
          - "host.docker.internal:host-gateway"
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: vmshare-nginx
    depends_on: [app]
    ports: ["80:80", "443:443"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/sites-enabled:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./app/static:/var/www/vmshare/static:ro
    restart: unless-stopped
