site_name: VM Access Platform
site_description: Run full Linux VMs in the browser via QEMU + noVNC
site_url: https://xvpaul.github.io/VM-share
repo_url: https://github.com/xvpaul/VM-share
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Overview: README.md
  - Architecture:
      - VM Lifecycle: LIFECYCLE.md
      - Authentication: AUTHENTICATION.md
      - Observability: OBSERVABILITY.md
  - API Reference: API.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
